[versions]
antlrKotlinVersion = "1.0.0-RC3"
org-jetbrains-kotlin-jvm = "1.9.20"

[libraries]
antlrKotlin = { group = "com.strumenta", name = "antlr-kotlin-runtime", version.ref = "antlrKotlinVersion" }

[plugins]
antlrKotlinPlugin = { id = "com.strumenta.antlr-kotlin", version.ref = "antlrKotlinVersion" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }