name: Build JVM artifacts
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar ckib
        uses: actions/upload-artifact@v3
        with:
          name: ckib
          path: |
            ckib/build/libs/*jar
      - name: Upload jar ckib-aries
        uses: actions/upload-artifact@v3
        with:
          name: ckib-aries
          path: |
            ckib-aries/build/libs/*jar
      - name: Upload jar ckib-openid
        uses: actions/upload-artifact@v3
        with:
          name: ckib-openid
          path: |
            ckib-openid/build/libs/*jar
