name: Build JVM artifacts
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar vclib
        uses: actions/upload-artifact@v3
        with:
          name: vclib
          path: |
            vclib/build/libs/*jar
      - name: Upload jar vclib-aries
        uses: actions/upload-artifact@v3
        with:
          name: vclib-aries
          path: |
            vclib-aries/build/libs/*jar
      - name: Upload jar vclib-openid
        uses: actions/upload-artifact@v3
        with:
          name: vclib-openid
          path: |
            vclib-openid/build/libs/*jar
